[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-arg=-sSTACK_SIZE=16mb",
    "-C", "link-arg=-sINITIAL_HEAP=512mb", # 128 MB RAM x 4 overhead
    "-C", "link-arg=-sEXIT_RUNTIME=1",
    "-C", "link-arg=-sMODULARIZE",
    "-C", "link-arg=-sEXPORT_ES6",
    "-C", "link-arg=-sEXPORT_NAME=emulator",
    "-C", "link-arg=-sEXPORTED_RUNTIME_METHODS=['FS','HEAPU8']",
    "-C", "link-arg=-sENVIRONMENT=worker",
    "-C", "link-arg=-gsource-map",
    "-C", "link-arg=-g2",
    "-C", "link-arg=-L./frontend_im/src",
    "-C", "link-arg=--js-library=./frontend_im/src/js_api/exports.js",
]
